#version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - database
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - symfony

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - symfony

  vue:
    build:
      context: ../vue
      dockerfile: Dockerfile
    volumes:
      - ../vue:/app
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony:
    driver: bridge
